### ISSUE TITLE
Is it possible to run only a selection of SAS-code?

### ISSUE THREAD

**Issue by rasmusrhl** [akanosora/language-sas#1]
This is not a bug, but I dont know where else to ask questions about use of 'language-sas'.

My question is:

Is it possible to run only a selection of SAS-code? (in SAS Enterprise Guide I would highlight a piece of code and press F3, and only the selection would run).

**Comment by zhen-huan-hu** [comment]
Unfortunately it is not possible. That is the limitation of the UNIX version of SAS. You have to run the entire program at once. If you want to run part of the code, you have to comment the other part out (using Ctrl+/)

**Comment by jphall663** [comment]
In windows, you can highlight code and run it. But not in *nix. 

Better places to ask about SAS include stackoverflow and the SAS communities. Good luck.
